Added script to wirelessly transfer compiled firmware sccript
macformula/racecar pull request #294
Opened 2024-11-06 02:42 UTC by saadatq

I have added the script for wireless transfer as well as a readme file with instructions. 

Please test out the script and let me know if there are any changes to be made.

2024-11-12 02:11 UTC, BlakeFreer requested changes

2024-11-12 02:11 UTC, BlakeFreer commented on scripts/canflash/cantransfer.sh
> +    echo "ERROR enter all arguements: sh cantransfer.sh 'bin_files' 'pi_username' 'host' 'destination_path'"
typo in argument

2024-11-12 02:11 UTC, BlakeFreer commented on scripts/canflash/cantransfer.sh
> +scp -r "$BIN_FILES/*" "$PI_USERNAME@$HOST:$DESTINATION_PATH"
only want to transfer a single binary file, not the whole folder

2024-11-12 02:11 UTC, BlakeFreer commented on scripts/canflash/README.md
> +type "ping [ip address]" in git bash
use backticks \` \` for commands and filepaths

2024-11-12 02:11 UTC, BlakeFreer commented on scripts/canflash/README.md
> +type "ping [ip address]" in git bash
Not everyone uses git bash, just say terminal.

Sentences should be capitalized and puctuated

2024-11-12 02:11 UTC, BlakeFreer commented on scripts/canflash/README.md
> +# How to run the cantransfer.sh script
Header levels should increase by one `#` at a time

2024-11-22 03:06 UTC, saadatq commented
Changes have been made as requested. Let me know if you need anything else from me.

2024-11-24 04:17 UTC, BlakeFreer commented
@CameronBeneteau can you test this on the Pi?

2024-11-27 07:20 UTC, CameronBeneteau requested changes
The file transfer works, but it's not as robust as we would like. Here are a few suggestions that will make it better:

I tested it with the pi and the current behaviour is as follows:
- The command fails when the destination path is a path (since it doesn't exist on the pi)
- The command fails when the destination path is left blank
- If the destination path is a file, the transferred file on the pi is named to this

I would recommend changing it for the following behaviour:
- A blank destination path will transfer the file (with the same name) to the pi's home directory
- A destination path that is a file name (not a directory) will transfer the file with the same name to the pi's home directory
- A destination path that is a directory will transfer the file to the same directory on the pi (this will require calling `mkdir` on the pi before the transfer

If you would like to test your changes and functionality on the pi please send me a message on teams and I can provide you with login information.

2024-11-27 07:20 UTC, CameronBeneteau commented on scripts/canflash/README.md
> +Run the script by using the command ``sh cantransfer.sh 'bin_files' 'pi_username' 'host' 'destination_path``.
Would recommend `host` is changed to `ip address`. Keeps it consistent with the above `ping` and I don't see us connecting to the pi's through other hostnames at the moment.

2024-11-27 07:20 UTC, CameronBeneteau commented on scripts/canflash/README.md
> +If there is no specific path to sent the file to the directory ``/home/pi_username/`` will work.
Please be more specific this is the default path (home directory). Any files or paths specified in the command will be relative to the home directory.

2024-12-07 05:19 UTC, saadatq commented
> * A destination path that is a file name (not a directory) will transfer the file with the same name to the pi's home directory

A little confused on what you meant by this. If the destination path is a file name is the bin file transferred to the pi's home directory or is a file on the computer with the same name transferred to the home directory?

2024-12-10 06:46 UTC, CameronBeneteau requested changes

2024-12-10 06:46 UTC, CameronBeneteau commented on scripts/canflash/cantransfer.sh
> +fi
No need for `home/username` as the script can only transfer files within this directory. There will be a permission error if you try to transfer a file to a directory that isn't under `home/username`. For `scp`, it is assumed the destination directory is relative to `/home/username`.

i.e. `sh cantransfer.sh test.txt username IP new-directory` will transfer the file to `home/username/new-directory/test.txt`

2024-12-10 06:46 UTC, CameronBeneteau commented on scripts/canflash/cantransfer.sh
> +
```suggestion
fi
    
```

2024-12-10 06:46 UTC, CameronBeneteau commented on scripts/canflash/cantransfer.sh
> +  DESTINATION_PATH="/home/$PI_USERNAME"
Not sure what `3SM4` is here, shouldn't it be checking `$2` or `$4`?

2024-12-21 06:40 UTC, saadatq commented
After testing the CAN flash transfer with the Pi, it should work as intended. Let me know if anything else is needed from me

2025-04-05 03:59 UTC, BlakeFreer commented
Closing, #424 implemented this behaviour using nicegui

2025-04-05 03:59 UTC, closed without merging