WIP: Rasi CAN implementation
macformula/racecar pull request #34
Opened 2024-01-16 18:02 UTC by samparent97

2024-01-18 03:56 UTC, BlakeFreer requested changes

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/CMakeLists.txt
Why has this been downgraded?

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/projects/DemoCan/README.md
update file for Demo Can

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/projects/DemoCan/platforms/windows/bindings.cc
either support CAN or remove the windows platform

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/projects/DemoCan/platforms/stm32f767/bindings.cc
either support stm32 or remove it as a platform for this project

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/projects/DemoCan/inc/app.h
remove unused app objects

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/raw_can_msg.h
do not use #define, see [Google Style Guide -> Preprocessor Macros](https://google.github.io/styleguide/cppguide.html#Preprocessor_Macros)

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/message_registry.h
needs a constructor to set the can_base_ variable. follow the style of the Button constructor in DemoProject/inc/app.h

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/bus_manager.h
needs a constructor to set the can_base_ variable. follow the style of the Button constructor in DemoProject/inc/app.h

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/message_registry.h
Why is this identical to BusManager?

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/projects/DemoCan/main.cc
Line 14: should not  be constructing an mcal in here, the veh_can variable should be specified as extern and provided in the bindings namespace

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/mcal/raspi/periph/can.h
what is "iface"? if it means "interface", replace it with the whole word as per [style guide](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules)

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/mcal/raspi/periph/can.cpp
remove "return" from `Setup()` since it is a void function

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/mcal/raspi/Toolchain.cmake
should PC be replaced with "Raspberry Pi"?

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/mcal/raspi/periph/can.cpp
is this file redundant with the .h file?

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/projects/DemoCan/main.cc
main cannot depend on thread and chrono if they are not available on all platforms. I am not sure if they are on stm and PC

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/projects/DemoCan/platforms/stm32f767/bindings.cc
add platform code for STM or remove it from this project

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/projects/DemoCan/platforms/windows/bindings.cc
add project support for Windows or remove this platform

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/bus_manager.h
line 11 & 17 & 31: follow the google style guide for template type names: they should be named like types (see last line of [this section](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules) for the note on template names and [this section](https://google.github.io/styleguide/cppguide.html#Type_Names) for naming guidelines)

In following with the pattern for app objects, the type name should match the shared::periph concept name, so replace `can_base` in line 11 with `Can` and `can_msg` with `CanMsg` in line 17 and 31

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/can_msg.h
Rename `CanMsg` to `CanMessage` as per [style guide naming](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules): do not shorten or abbreviate just to save horizontal space

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/can_msg.h
remove `cstdint` include since it is unused

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/bus_manager.h
why is `CanMsg` from `shared::periph`? shouldn't it be from `shared::comms`?

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/bus_manager.h
needs a constructor to set the can_base instance variable. Follow the constructor format of Button in DemoProject/inc/app.h

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/message_registry.h
is this identical to BusManager?

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/comms/can/raw_can_msg.h
[do not use preprocessor macros](https://google.github.io/styleguide/cppguide.html#Preprocessor_Macros)

2024-01-18 03:56 UTC, BlakeFreer commented on firmware/shared/periph/can.h
should evaluate if `Setup()` is required in the concept since (I believe) it is not a key function of the CanBase functionality. mcal implementation of CanBase can optionally define a setup method that gets called in the `bindings::Initialize()` function, but if more control is needed then it can be required in the concept

2024-01-18 22:39 UTC, samparent97 commented on firmware/CMakeLists.txt
A lot of the changeset is there just to get something working, hence the draft PR

2024-03-23 19:12 UTC, BlakeFreer requested changes
As another note, I think we should shorten the `shared::comms::can` namespace to just `shared::can`. There will not be another shared item called `can` so this seems like an unnecessary specification. I like the folder structure though so it doesn't need to change.

2024-03-23 19:12 UTC, BlakeFreer commented on firmware/projects/DemoCan/platforms/raspi/bindings.h
we no longer use `bindings.h`. Move includes to `bindings.cc`

2024-03-23 19:12 UTC, BlakeFreer commented on firmware/projects/DemoCan/main.cc
> +#include "bindings.h"
we don't use `bindings.h` anymore. You should `extern` reference a shared `CanBase` and bind an mcal object to it in `bindings.cc`. See DemoProject on the main branch for an example

2024-03-23 19:12 UTC, BlakeFreer commented on firmware/projects/DemoCan/main.cc
> +generated::can::DemoCanVehMsgRegistry veh_can_regitry{};
typo, missing an `s` in `veh_can_regitry`

2024-03-23 19:12 UTC, BlakeFreer commented on firmware/projects/DemoProject/platforms/stm32f767/cubemx/board_config.ioc
> +MxCube.Version=6.10.0
What version of cubemx are we going to use? I specified 6.8.1 in the firmware readme and we all need to be synchronized.

2024-03-23 19:12 UTC, BlakeFreer commented on firmware/shared/comms/can/can_bus.h
> +private:
private section after public

2024-03-23 19:12 UTC, BlakeFreer commented on firmware/shared/comms/can/can_bus.h
> +        std::cerr << "Reading queue" << std::endl;
how will this behave on stm? does it have cerr?

2024-03-23 19:12 UTC, BlakeFreer commented on firmware/shared/comms/can/can_bus.h
> +        return;
why return?

2024-03-23 19:12 UTC, BlakeFreer commented on firmware/shared/comms/can/can_msg.h
agreed, leave as Msg

2024-03-23 19:12 UTC, BlakeFreer commented on firmware/shared/comms/can/can_msg.h
> +class DemoCanVehMsgRegistry;
why is this in Shared? Is it only for the DemoCan project?

2024-03-25 01:24 UTC, BlakeFreer commented on firmware/shared/comms/can/bus_manager.h
understood, CanBase is the peripheral

2024-03-25 01:26 UTC, BlakeFreer commented on firmware/projects/DemoCan/inc/etl_profile.h
> +#define ETL_POLYMORPHIC_UNORDERED_MAP
this `#define` must occur before any etl headers are included, so it must be declared wherever the unordered map is included

2024-03-25 01:28 UTC, BlakeFreer commented on firmware/CMakeLists.txt
> +	${DIR_GENERATED}
not if files are included with `generated/...`

2024-03-25 01:31 UTC, BlakeFreer commented on firmware/projects/DemoCan/inc/etl_profile.h
> +#define ETL_POLYMORPHIC_UNORDERED_MAP
seems like the unordered map is used in generated/msg_registry.h. The auto-generator must include this `#define` statement

2024-03-25 01:32 UTC, BlakeFreer commented on firmware/mcal/raspi/periph/can.h
> +#include "third-party/etl/include/etl/queue.h"
will be addressed later with #81

2024-03-25 16:11 UTC, samparent97 commented
> As another note, I think we should shorten the `shared::comms::can` namespace to just `shared::can`. There will not be another shared item called `can` so this seems like an unnecessary specification. I like the folder structure though so it doesn't need to change.

I personally think it makes sense to have this namespace to distinguish communication protocols from within the shared folder.

2024-03-25 23:44 UTC, BlakeFreer commented
> > As another note, I think we should shorten the `shared::comms::can` namespace to just `shared::can`. There will not be another shared item called `can` so this seems like an unnecessary specification. I like the folder structure though so it doesn't need to change.
> 
> I personally think it makes sense to have this namespace to distinguish communication protocols from within the shared folder.

OK will leave as is

2024-03-30 16:48 UTC, BlakeFreer commented on firmware/projects/DemoCan/inc/etl_profile.h
> +#define ETL_POLYMORPHIC_UNORDERED_MAP
check how etl finds header profile

2024-03-30 17:02 UTC, BlakeFreer commented on firmware/.gitignore
lev it .gitignore

2024-03-30 17:09 UTC, BlakeFreer commented on firmware/mcal/raspi/periph/can.h
> +        while(true) {
resolved, rpi specific

2024-03-30 17:12 UTC, BlakeFreer commented on firmware/mcal/raspi/periph/can.h
> +            close(sock_);
leave for now

2024-03-30 17:32 UTC, BlakeFreer commented on firmware/shared/comms/can/can_bus.h
> +        std::cerr << "Reading queue" << std::endl;
will be removed

2024-03-30 17:33 UTC, BlakeFreer commented on firmware/shared/comms/can/can_bus.h
> +        return;
will be removed

2024-03-30 17:35 UTC, BlakeFreer commented on firmware/shared/comms/can/can_msg.h
> +class DemoCanVehMsgRegistry;
will be removed

2024-03-30 17:36 UTC, BlakeFreer commented on firmware/mcal/raspi/periph/can.h
> +            {
will add brief comment

2024-04-10 22:05 UTC, samparent97 commented
All comments resolved. Rebased in new branch which required new PR #98

2024-04-10 22:05 UTC, closed without merging