Format string
macformula/racecar pull request #368
Opened 2024-12-30 03:11 UTC by ManushPatell

- Implemented std::format in C++ to the appropriate files. I wasn't able to check all the files through testing but the demo for BasicIO and Blink work as intended

2024-12-31 16:47 UTC, BlakeFreer requested changes

2024-12-31 16:47 UTC, BlakeFreer commented on firmware/mcal/cli/periph/can.h
> +        "[ "<< std::format("{} {:02X}", iface_ can_tx.msg.header.id) << "] ";
Where does this get printed? Why aren't the square brackets in the format string? Also I don't think the format string is equivalent to the old statement

2024-12-31 16:47 UTC, BlakeFreer commented on firmware/mcal/cli/periph/can.h
> +            std::cout << std::format("{:02X} ", static_cast<int>(can_tx_msg.data[i]));
Do we need static cast still?

2024-12-31 16:47 UTC, BlakeFreer commented on firmware/mcal/cli/periph/gpio.h
> +        std::cout <<, std::format("Reading DigitalInput {}", name_ ) << std::endl;
What's the comma for? Looks like it'll cause an error

2024-12-31 16:47 UTC, BlakeFreer commented on firmware/mcal/cli/periph/gpio.h
> +        std::cout << std::format("| Value was {}", (value ? "true": "false" )) << std::endl;
Remove () around the ternary statement. Also lost a space in the string

2024-12-31 16:47 UTC, BlakeFreer commented on firmware/mcal/cli/periph/gpio.h
> +        std::cout << std::format("Setting DigitalOutput Channel {} to {}", name_, (value ? "true": "false") ) << std::endl;
Remove () around ternary

2024-12-31 16:47 UTC, BlakeFreer commented on firmware/mcal/cli/periph/gpio.h
> +        std::cout << std::format("Setting DigitalOutput Channel {} to {}", name_, (value ? "true": "false") ) << std::endl;
Check the cpp format string spec. Do we need the ternary operator or is there a simpler way to print a string version of a Boolean

2024-12-31 16:47 UTC, BlakeFreer commented on firmware/mcal/cli/periph/pwm.h
> +        std::cout << std::format("Stopping PWN {}", name_) << std::endl;
Spelling

2024-12-31 16:47 UTC, BlakeFreer commented on firmware/mcal/cli/periph/pwm.h
> +        std::cout << std::format("Setting PWN {} duty cycle to {:.3f} %", name_, duty_cycle_) << std::endl;
Spelling

2024-12-31 16:47 UTC, BlakeFreer commented on firmware/mcal/cli/periph/pwm.h
> +        std::cout << std::format("Setting PWN {} duty cycle to {:.3f} %", name_, duty_cycle_) << std::endl;
No space after percent. Good use of .3f but that'll print a lot of decimals like 93.123. Is there a way to print 3 sig figs instead? (Don't just change to .1f)

2025-01-03 03:58 UTC, ManushPatell commented on firmware/mcal/cli/periph/can.h
> +            std::cout << std::format("{:02X} ", static_cast<int>(can_tx_msg.data[i]));
i think so, std::format doesn't seem to do anything to support the conversion to an int. I think without the cast, it would interpret it as an unsigned char and therefore give the ascii

2025-01-03 05:59 UTC, BlakeFreer commented on firmware/mcal/cli/periph/can.h
> +            std::cout << std::format("{:02X} ", static_cast<int>(can_tx_msg.data[i]));
ok, have you tested this? what happens if you remove static cast?

2025-01-04 05:37 UTC, BlakeFreer requested changes
one small note, otherwise good.

2025-01-04 05:37 UTC, BlakeFreer commented on firmware/mcal/cli/periph/gpio.h
> +        std::cout << std::format(" | Value was {}", value ? "true": "false") << std::endl;
can the boolean expression be simplified?

2025-01-06 03:55 UTC, ManushPatell commented on firmware/mcal/cli/periph/can.h
> +            std::cout << std::format("{:02X} ", static_cast<int>(can_tx_msg.data[i]));
I didn't notice anything different when I removed the static cast

2025-01-06 19:38 UTC, BlakeFreer requested changes

2025-01-06 19:38 UTC, BlakeFreer commented on firmware/mcal/cli/periph/gpio.h
> +        std::cout << std::format(" | Value was {}", value ? "true": "false") << std::endl;
Unresolving, this should be simplified. Look at what you've done for `DigitalOutput::Set()`

2025-01-06 19:38 UTC, BlakeFreer commented on firmware/mcal/cli/periph/can.h
> +            std::cout << std::format("{:02X} ", static_cast<int>(can_tx_msg.data[i]));
Ok then let's remove it. No point having useless code

2025-01-07 03:35 UTC, BlakeFreer commented
Still need to update:
- mcal/cli/periph: adc.h, analog_output.h

2025-01-07 20:55 UTC, BlakeFreer requested changes

2025-01-07 20:55 UTC, BlakeFreer commented on firmware/mcal/cli/periph/analog_output.h
> +        std::cout << std::format("Setting AnalogOutput {} to {} V", name_, voltage) << std::endl;
floating point numbers should almost always be rounded for printing. use 3 decimal places for voltage.

2025-01-08 18:29 UTC, merged