Can implementation; DemoCan project with Raspi platform impl
macformula/racecar pull request #98
Opened 2024-04-09 21:45 UTC by samparent97

2024-04-13 21:35 UTC, BlakeFreer commented on firmware/CMakeLists.txt
> +set(DIR_ETL "${CMAKE_CURRENT_SOURCE_DIR}/third-party/etl/include")
`add_subirectory(${CUR_SRC}.../etl')

2024-04-13 23:04 UTC, BlakeFreer requested changes

2024-04-13 23:04 UTC, BlakeFreer commented on scripts/cangen/can_gen.py
> +            shift_amounts[-i] = (i * self.EIGHT_BITS) - num_zeroes
replace with 
`return list(range(-num_zeros, 64-num_zeros, 8))[::-1]`

2024-04-13 23:04 UTC, BlakeFreer commented
rebase

2024-04-14 02:46 UTC, samparent97 commented on firmware/mcal/raspi/periph/can.h
> +    static constexpr uint8_t kMaxMsgBytes = 8;
yes

2024-04-14 02:49 UTC, samparent97 commented on firmware/mcal/raspi/periph/can.h
> +    void Send(const shared::can::RawCanMsg& can_tx_msg) {
removed the using

2024-04-14 02:56 UTC, samparent97 commented on firmware/projects/DemoCan/generated/can_messages.h
> +    float sensor6 = 0;
demo can has them in this reversed order by the bits in the raw message

2024-04-14 03:04 UTC, samparent97 commented on firmware/projects/DemoCan/generated/msg_registry.h
added #102

2024-04-14 03:05 UTC, samparent97 commented on firmware/projects/DemoCan/main.cc
> +    while (1) {
```suggestion
    while (true) {
```

2024-04-14 03:39 UTC, merged